DefaultContentLanguage = "en"
author = ""
baseURL = "https://dcw.fairbank.fas.harvard.edu"
defaultContentLanguageInSubdir = true
enableInlineShortcodes = true
enableRobotsTXT = true
languageCode = "en-us"
theme = "vnovel"
title = "Digital China Worldwide"

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "G-1234567890"

# Disqus Comment System
#disqusShortname = ""

[params]
# The number of articles to be displayed on a single page.
api_url = ""
paginator_pages = "6"

# Site logo.
#logo = ""

# [params.homepage_meta_tags]
# meta_description = "Pixiv-like theme for novels."
# meta_og_description = "Pixiv-like theme for novels."
# meta_og_image = "https://vnovel.pages.dev/img/thumbnail.png"
# meta_og_title = "VNovel"
# meta_og_type = "website"
# meta_og_url = "https://vnovel.pages.dev"
# meta_twitter_card = "summary_large_image"
# meta_twitter_creator = "@username"
# meta_twitter_site = "@username"

[outputs]
home = ["HTML", "RSS", "JSON"]

[outputFormats.JSON]
baseName = "index"
isPlainText = true
mediaType = "application/json"

# [params.meilisearch]
#   host = "https://your-meilisearch-host.com"
#   apiKey = "your-meilisearch-api-key"
#   index = "your-index-name"
