[[main]]
identifier = "resources"
name = "Resources"
url = "/en/resources/"
weight = 1

[[main]]
identifier = "creators"
name = "Creators"
url = "/en/creators/"
weight = 2

[[main]]
identifier = "Search"
name = "search"
url = "/en/search/"
weight = 3

[[main]]
identifier = "about"
name = "About"
url = "/en/about/"
weight = 4

[[main]]
identifier = "participate"
name = "Participate"
url = "/en/participate/"
weight = 5
