[[main]]
identifier = "resources"
name = "Resources"
url = "/zh-cn/resources/"
weight = 1

[[main]]
identifier = "creators"
name = "Creators"
url = "/zh-cn/creators/"
weight = 2

[[main]]
identifier = "about"
name = "About"
url = "/zh-cn/about/"
weight = 3

[[main]]
identifier = "participate"
name = "Participate"
url = "/en/participate/"
weight = 4
