[[main]]
identifier = "resources"
name = "Resources"
url = "/ko/resources/"
weight = 1

[[main]]
identifier = "creators"
name = "Creators"
url = "/ko/creators/"
weight = 2

[[main]]
identifier = "search"
name = "Search"
url = "/en/search/"
weight = 3

[[main]]
identifier = "about"
name = "About"
url = "/ko/about/"
weight = 4

[[main]]
identifier = "participate"
name = "Participate"
url = "/ko/participate/"
weight = 5
